version: '3.9'

services:
  route-calculation-service:
    build:
      context: ./route-calculation-service
    container_name: route-calculation-service
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: route-calculation-service
      SERVER_PORT: 8080
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: INFO
      USER_PROFILE_SERVICE_URL: http://user-profile-service:8080
      INCIDENT_SERVICE_URL: http://notification-service:8080
      ENVIRONMENTAL_DATA_SERVICE_URL: http://environmental-data-service:8081

  environmental-data-service:
    build:
      context: ./environmental-data-service
    container_name: environmental-data-service
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_NAME: environmental-data-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://environmental-database:5432/environmental-data
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      GEOJSON_URL: https://data.smartdublin.ie/dataset/4976e11e-a015-4ef9-9179-dc7c27fb5a81/resource/ec7f3108-c12b-4e07-b482-470f28f52aca/download/airview_dublincity_roaddata_ugm3
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - environmental-database

  environmental-database:
    image: postgres:15
    container_name: environmental-database
    ports:
      - "6543:5432"  # Host port 6543 mapped to container port 5432
    environment:
      POSTGRES_DB: environmental-data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - env_db_data:/var/lib/postgresql/data

  notification-service:
    build:
      context: ./real-time-incident-notification-service
    container_name: notification-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-database:5432/real-time-notification-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: real-time-notification-service
      TWILIO_ACCOUNT_SID: your_account_sid
      TWILIO_AUTH_TOKEN: your_auth_token
      TWILIO_PHONE_NUMBER: +19876543210
      DEMO_PHONE_NUMBER: +1234567890
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - notification-database

  notification-database:
    image: postgres:15
    container_name: notification-database
    ports:
      - "7543:5432"  # Host port 7543 mapped to container port 5432
    environment:
      POSTGRES_DB: real-time-notification-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: real-time-notification-service
    volumes:
      - notification_db_data:/var/lib/postgresql/data

  user-profile-service:
    build:
      context: ./user-profile-information-store
    container_name: user-profile-service
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-profile-database:5432/user-profile-information-store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: user-profile-information-store
      AUTH0_CLIENT_ID: tmGAY4qxdv5KsNtk4rzTbLl1yinCwQH4
      AUTH0_CLIENT_SECRET: 2hukdg7i-kp-LlCTofBx0--1wY_zaEZKReKZF5-zQ3PiBi8I9TvEwheMjJWX0xl3
      AUTH0_DOMAIN: https://dev-6o86uui2n8dzxn5m.us.auth0.com
      AUTH0_AUDIENCE: https://dev-6o86uui2n8dzxn5m.us.auth0.com/api/v2/
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - user-profile-database

  user-profile-database:
    image: postgres:15
    container_name: user-profile-database
    ports:
      - "8543:5432"  # Host port 8543 mapped to container port 5432
    environment:
      POSTGRES_DB: user-profile-information-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user-profile-information-store
    volumes:
      - user_profile_db_data:/var/lib/postgresql/data

volumes:
  env_db_data:
  notification_db_data:
  user_profile_db_data:
