services:
  route-calculation-service:
    build:
      context: ./route-calculation-service
    container_name: ${ROUTE_SERVICE_NAME}
    ports:
      - "${ROUTE_SERVICE_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_APPLICATION_NAME: ${ROUTE_SERVICE_NAME}
      SERVER_PORT: ${ROUTE_SERVICE_PORT}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: ${LOGGING_LEVEL_SPRING}
      USER_PROFILE_SERVICE_URL: ${USER_PROFILE_SERVICE_URL}
      INCIDENT_SERVICE_URL: ${INCIDENT_SERVICE_URL}
      ENVIRONMENTAL_DATA_SERVICE_INTERNAL_URL: http://environmental-data-service:8080
      ENVIRONMENTAL_DATA_SERVICE_URL: ${ENVIRONMENTAL_DATA_SERVICE_URL}
      OSM_FILE_PATH: /app/data/ireland-and-northern-ireland-latest.osm.pbf
      GTFS_PATH: /app/gtfs

  environmental-data-service:
    build:
      context: ./environmental-data-service
    container_name: ${ENV_SERVICE_NAME}
    ports:
      - "${ENV_SERVICE_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_APPLICATION_NAME: ${ENV_SERVICE_NAME}
      SPRING_DATASOURCE_URL: ${ENV_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${ENV_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ENV_DATASOURCE_PASSWORD}
      GEOJSON_URL: ${GEOJSON_URL}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
    depends_on:
      - environmental-database

  environmental-database:
    image: postgres:15
    container_name: environmental-database
    ports:
      - "${ENV_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${ENV_DB_NAME}
      POSTGRES_USER: ${ENV_DB_USER}
      POSTGRES_PASSWORD: ${ENV_DB_PASSWORD}
    volumes:
      - env_db_data:/var/lib/postgresql/data

  notification-service:
    build:
      context: ./real-time-incident-notification-service
    container_name: ${NOTIF_SERVICE_NAME}
    ports:
      - "${NOTIF_SERVICE_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: ${NOTIF_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${NOTIF_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${NOTIF_DATASOURCE_PASSWORD}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      DEMO_PHONE_NUMBER: ${DEMO_PHONE_NUMBER}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    depends_on:
      - notification-database

  notification-database:
    image: postgres:15
    container_name: notification-database
    ports:
      - "${NOTIF_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${NOTIF_DB_NAME}
      POSTGRES_USER: ${NOTIF_DB_USER}
      POSTGRES_PASSWORD: ${NOTIF_DB_PASSWORD}
    volumes:
      - notification_db_data:/var/lib/postgresql/data

  user-profile-service:
    build:
      context: ./user-profile-information-store
    container_name: ${USER_SERVICE_NAME}
    ports:
      - "${USER_SERVICE_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: ${USER_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${USER_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${USER_DATASOURCE_PASSWORD}
      USER_SERVICE_URL: http://${USER_SERVICE_NAME}:${USER_SERVICE_PORT}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      REWARD_SERVICE_INTERNAL_URL: http://reward-service:8080
    depends_on:
      - user-profile-database

  user-profile-database:
    image: postgres:15
    container_name: user-profile-database
    ports:
      - "${USER_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - user_profile_db_data:/var/lib/postgresql/data

  reward-service:
    build:
      context: ./reward-service
    container_name: ${REWARD_SERVICE_NAME}
    ports:
      - "${REWARD_SERVICE_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_APPLICATION_NAME: ${REWARD_SERVICE_NAME}
      SPRING_DATASOURCE_URL: ${REWARD_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${REWARD_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${REWARD_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
    depends_on:
      - reward-database

  reward-database:
    image: postgres:15
    container_name: reward-database
    ports:
      - "${REWARD_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${REWARD_DB_NAME}
      POSTGRES_USER: ${REWARD_DB_USER}
      POSTGRES_PASSWORD: ${REWARD_DB_PASSWORD}
    volumes:
      - reward_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - environmental-database
      - notification-database
      - user-profile-database
      - reward-database

  pyroscope:
    image: pyroscope/pyroscope:latest
    ports:
      - "4040:4040"
    environment:
      PYROSCOPE_SERVER_ADDRESS: ${PYROSCOPE_SERVER_ADDR}
      PYROSCOPE_AUTH_USER: ${PYROSCOPE_USER}
      PYROSCOPE_AUTH_PASSWORD: ${PYROSCOPE_PASSWORD}
    command: server

volumes:
  pgadmin_data:
  env_db_data:
  notification_db_data:
  user_profile_db_data:
  reward_db_data:
